version: '3'
services:
  content_core_db-dev:
    image: postgres
    container_name: content_core_db
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: content_core_db
    ports:
      - 5444:5432