version: '3'
services:
  content_core_db:
    image: postgres
    container_name: container_core_db
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: container_core_db
  content_core:
    image: 'he305/content-core:latest'
    restart: always
    build:
      context: .
    container_name: content_core
    ports:
      - 8081:8081
    depends_on:
      - content_core_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://content_core_db:5432/container_core_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin