server:
  port: 8081

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        use_sql_comment: true
        format_sql: true
  datasource:
    initialization-mode: always
    url: jdbc:postgresql://127.0.0.1:5444/content_core_db
    username: admin
    password: admin

jwt:
  secret.key: dGhpcyBpcyBteSB2ZXJ5IHNlY3JldCBrZXkgdGhhdCBub2JvZHkga25vd3MgYWJvdXQuIGkgYW0gc3VyZSB0aGF0IG5vYm9keSB3aWxsIGV2ZXIga25vdyBhYm91dCB0aGUgY29udGVudHMgb2YgdGhpcyBrZXkuIGkgaG9wZSB0aGlzIGlzIGVub3VnaCBmb3IgMjU2IGJpdHM=
  expiration-min: 120
  issuer: content-core
  refresh:
    key: YmJsYWJsYWxiYWxzYWRsYWRxd2Vybmp3ZXVibmFzbmRhaWJuIGRpd3FuZWRrelNtZHBhRE9TYWFzZG5hc2RmbnVpYnF3aXVxIGVxZHFxZGRhc2Q=
    expiration-days: 30

auth:
  service-register-key: exampleserviceregisterkey