server:
  port: 8081

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        use_sql_comment: true
        format_sql: true
  datasource:
    initialization-mode: always
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

jwt:
  public.key: classpath:example_app.pub
  private.key: classpath:example_app.key
  secret.key: very-secret-key
  expiration-min: 120
  issuer: content-core